module.exports = {    
    REGISTER_SERVER: 'SERVER REGISTRATION',
    REGISTER_CLIENT: 'CLIENT REGISTRATION',
    NO_CLIENTS_CONNECTED: 'NO CLIENTS CONNECTED',
    SERVER_NOT_CONNECTED: 'SERVER NOT CONNECTED',
    SERVER_ALREADY_REGISTERED: 'SERVER ALREADY REGISTERED',
    KEEP_ALIVE: 'KEEP ALIVE'
}