module.exports = {    
    REGISTER_SERVER: 'SERVER_REGISTRATION_MESSAGE',
    NO_CLIENTS_CONNECTED: 'NO CLIENTS CONNECTED',
    SERVER_NOT_CONNECTED: 'SERVER NOT CONNECTED',
    SERVER_ALREADY_REGISTERED: 'SERVER ALREADY REGISTERED'
}